apiVersion: v1
kind: Service
metadata:
  name: cypc311
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "cypc311"
    port: 8080
  selector:
    app: cypc311
